---
-   name: Create deploy user
    ansible.builtin.user:
        name: deploy
        password: '!'
        groups:
            - docker
        shell: /bin/bash
        create_home: yes
        state: present
