---
-   name: Upgrade and Maintain System
    hosts: all
    remote_user: root
    tasks:
        -   name: Update, upgrade, and clean APT packages
            ansible.builtin.apt:
                update_cache: yes
                upgrade: dist
                autoclean: yes
                autoremove: yes
