---
-   name: Set periodic Docker Dind prune
    ansible.builtin.cron:
        name: docker-dind-prune
        job: '/bin/sh -c "cd {{ jenkins_path }} && docker compose exec docker docker system prune -af --filter until=360h"'
        minute: '0'
        hour: '2'
